import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ModalController from "@/component/ModalController";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-background relative h-screen w-screen">
          <div className="relative m-auto max-w-10/12 py-3">
            <ModalController />
            {children}
          </div>
          <div
            id="texture"
            className="pointer-events-none absolute inset-0 bg-repeat mix-blend-multiply"
          ></div>
        </div>
      </body>
    </html>
  );
}
